services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nogal
      POSTGRES_PASSWORD: nogal
      POSTGRES_DB: nogal
    ports:
      - "5432:5432"
    volumes:
      - nogal-postgres-data:/var/lib/postgresql/data

volumes:
  nogal-postgres-data:
