[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm@11.9.0", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo run build --filter=@nogal/api..."]

[start]
cmd = "node apps/api/dist/main.js"
